language: ruby
rvm:
  - 2.0.0
script:
  - chmod +x script/build
  - ./scripts/build
after_success:
  - chmod +x script/deploy
  - ./scripts/deploy
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
# blacklist
branches:
  except:
    - master

# whitelist
branches:
  only:
    - scheduled
