url: http://localhost:4000

comments:
    disqus: 
    disquscommentcount: 
#    isso: "comments.mysite.org"

analytics:
    google:
    
defaults:
    -
        scope:
            path: ""
            type: "posts"
        values:
            comments: false
future: false
links:
   rss: site.xml # your feedburner url
